/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BolsaRouteImport } from './routes/bolsa'
import { Route as TallerRouteImport } from './routes/taller'
import { Route as ColeccionSlugRouteImport } from './routes/coleccion.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BolsaRoute = BolsaRouteImport.update({
  id: '/bolsa',
  path: '/bolsa',
  getParentRoute: () => rootRouteImport,
} as any)
const TallerRoute = TallerRouteImport.update({
  id: '/taller',
  path: '/taller',
  getParentRoute: () => rootRouteImport,
} as any)
const ColeccionSlugRoute = ColeccionSlugRouteImport.update({
  id: '/coleccion/$slug',
  path: '/coleccion/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bolsa': typeof BolsaRoute
  '/taller': typeof TallerRoute
  '/coleccion/$slug': typeof ColeccionSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bolsa': typeof BolsaRoute
  '/taller': typeof TallerRoute
  '/coleccion/$slug': typeof ColeccionSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bolsa': typeof BolsaRoute
  '/taller': typeof TallerRoute
  '/coleccion/$slug': typeof ColeccionSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bolsa' | '/taller' | '/coleccion/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bolsa' | '/taller' | '/coleccion/$slug'
  id: '__root__' | '/' | '/bolsa' | '/taller' | '/coleccion/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BolsaRoute: typeof BolsaRoute
  TallerRoute: typeof TallerRoute
  ColeccionSlugRoute: typeof ColeccionSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bolsa': {
      id: '/bolsa'
      path: '/bolsa'
      fullPath: '/bolsa'
      preLoaderRoute: typeof BolsaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taller': {
      id: '/taller'
      path: '/taller'
      fullPath: '/taller'
      preLoaderRoute: typeof TallerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coleccion/$slug': {
      id: '/coleccion/$slug'
      path: '/coleccion/$slug'
      fullPath: '/coleccion/$slug'
      preLoaderRoute: typeof ColeccionSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BolsaRoute: BolsaRoute,
  TallerRoute: TallerRoute,
  ColeccionSlugRoute: ColeccionSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
