/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BolsaRouteImport } from './routes/bolsa'
import { Route as GaleriaRouteImport } from './routes/galeria'
import { Route as PersonalRouteImport } from './routes/personal'
import { Route as PersonalizarRouteImport } from './routes/personalizar'
import { Route as TallerRouteImport } from './routes/taller'
import { Route as TiendaRouteImport } from './routes/tienda'
import { Route as ColeccionSlugRouteImport } from './routes/coleccion.$slug'
import { Route as TiendaProductSlugRouteImport } from './routes/tienda.$productSlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BolsaRoute = BolsaRouteImport.update({
  id: '/bolsa',
  path: '/bolsa',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaRoute = GaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalRoute = PersonalRouteImport.update({
  id: '/personal',
  path: '/personal',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalizarRoute = PersonalizarRouteImport.update({
  id: '/personalizar',
  path: '/personalizar',
  getParentRoute: () => rootRouteImport,
} as any)
const TallerRoute = TallerRouteImport.update({
  id: '/taller',
  path: '/taller',
  getParentRoute: () => rootRouteImport,
} as any)
const TiendaRoute = TiendaRouteImport.update({
  id: '/tienda',
  path: '/tienda',
  getParentRoute: () => rootRouteImport,
} as any)
const ColeccionSlugRoute = ColeccionSlugRouteImport.update({
  id: '/coleccion/$slug',
  path: '/coleccion/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TiendaProductSlugRoute = TiendaProductSlugRouteImport.update({
  id: '/$productSlug',
  path: '/$productSlug',
  getParentRoute: () => TiendaRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bolsa': typeof BolsaRoute
  '/galeria': typeof GaleriaRoute
  '/personal': typeof PersonalRoute
  '/personalizar': typeof PersonalizarRoute
  '/taller': typeof TallerRoute
  '/tienda': typeof TiendaRouteWithChildren
  '/coleccion/$slug': typeof ColeccionSlugRoute
  '/tienda/$productSlug': typeof TiendaProductSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bolsa': typeof BolsaRoute
  '/galeria': typeof GaleriaRoute
  '/personal': typeof PersonalRoute
  '/personalizar': typeof PersonalizarRoute
  '/taller': typeof TallerRoute
  '/tienda': typeof TiendaRouteWithChildren
  '/coleccion/$slug': typeof ColeccionSlugRoute
  '/tienda/$productSlug': typeof TiendaProductSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bolsa': typeof BolsaRoute
  '/galeria': typeof GaleriaRoute
  '/personal': typeof PersonalRoute
  '/personalizar': typeof PersonalizarRoute
  '/taller': typeof TallerRoute
  '/tienda': typeof TiendaRouteWithChildren
  '/coleccion/$slug': typeof ColeccionSlugRoute
  '/tienda/$productSlug': typeof TiendaProductSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bolsa'
    | '/galeria'
    | '/personal'
    | '/personalizar'
    | '/taller'
    | '/tienda'
    | '/coleccion/$slug'
    | '/tienda/$productSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bolsa'
    | '/galeria'
    | '/personal'
    | '/personalizar'
    | '/taller'
    | '/tienda'
    | '/coleccion/$slug'
    | '/tienda/$productSlug'
  id:
    | '__root__'
    | '/'
    | '/bolsa'
    | '/galeria'
    | '/personal'
    | '/personalizar'
    | '/taller'
    | '/tienda'
    | '/coleccion/$slug'
    | '/tienda/$productSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BolsaRoute: typeof BolsaRoute
  GaleriaRoute: typeof GaleriaRoute
  PersonalRoute: typeof PersonalRoute
  PersonalizarRoute: typeof PersonalizarRoute
  TallerRoute: typeof TallerRoute
  TiendaRoute: typeof TiendaRouteWithChildren
  ColeccionSlugRoute: typeof ColeccionSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bolsa': {
      id: '/bolsa'
      path: '/bolsa'
      fullPath: '/bolsa'
      preLoaderRoute: typeof BolsaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria': {
      id: '/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof GaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personal': {
      id: '/personal'
      path: '/personal'
      fullPath: '/personal'
      preLoaderRoute: typeof PersonalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personalizar': {
      id: '/personalizar'
      path: '/personalizar'
      fullPath: '/personalizar'
      preLoaderRoute: typeof PersonalizarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taller': {
      id: '/taller'
      path: '/taller'
      fullPath: '/taller'
      preLoaderRoute: typeof TallerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tienda': {
      id: '/tienda'
      path: '/tienda'
      fullPath: '/tienda'
      preLoaderRoute: typeof TiendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coleccion/$slug': {
      id: '/coleccion/$slug'
      path: '/coleccion/$slug'
      fullPath: '/coleccion/$slug'
      preLoaderRoute: typeof ColeccionSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tienda/$productSlug': {
      id: '/tienda/$productSlug'
      path: '/$productSlug'
      fullPath: '/tienda/$productSlug'
      preLoaderRoute: typeof TiendaProductSlugRouteImport
      parentRoute: typeof TiendaRoute
    }
  }
}

interface TiendaRouteChildren {
  TiendaProductSlugRoute: typeof TiendaProductSlugRoute
}

const TiendaRouteChildren: TiendaRouteChildren = {
  TiendaProductSlugRoute: TiendaProductSlugRoute,
}

const TiendaRouteWithChildren =
  TiendaRoute._addFileChildren(TiendaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BolsaRoute: BolsaRoute,
  GaleriaRoute: GaleriaRoute,
  PersonalRoute: PersonalRoute,
  PersonalizarRoute: PersonalizarRoute,
  TallerRoute: TallerRoute,
  TiendaRoute: TiendaRouteWithChildren,
  ColeccionSlugRoute: ColeccionSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
